export enum EVENTS_SOCKET {
  NEW_MESSAGE = 'MESSAGE:CREATE',
  NEW_DIALOG = 'MESSAGE:DIALOG',
  READ_MESSAGE = 'MESSAGE:READ',
  TYPING_MESSAGE = 'MESSAGE:TYPING',
  START_CALL = 'CALL:START',
  ACCEPT_CALL = 'ACCEPT_CALL',
  DECLINE_CALL = 'CALL:DECLINE',
  RELAY_ICE = 'RELAY_ICE',
  RELAY_SESSION_DESCRIPTION = 'RELAY_',
  SESSION_DESCRIPTION = 'SESSION_DESCRIPTION',
  ICE_CANDIDATE = 'ICE_CANDIDATE',
}
