export enum EVENTS_SOCKET {
  NEW_MESSAGE = 'MESSAGE:CREATE',
  NEW_DIALOG = 'MESSAGE:DIALOG',
  READ_MESSAGE = 'MESSAGE:READ',
  TYPING_MESSAGE = 'MESSAGE:TYPING',
  START_CALL = 'CALL:START',
  ACCEPT_CALL = 'CALL:ACCEPT',
  DECLINE_CALL = 'CALL:DECLINE',
  SET_MEDIA_DESCRIPTION = 'SET_MEDIA_DESCRIPTION',
  RELAY_ICE = 'RELAY_ICE',
  RELAY_SDP = 'RELAY_SDP',
  SESSION_DESCRIPTION = 'SESSION_DESCRIPTION',
  ICE_CANDIDATE = 'ICE_CANDIDATE',
}
