export const PATHS = ['/user/login', '/user/signup']

export enum EVENTS_SOCKET {
  CONNECTION = 'connection',
  NEW_MESSAGE = 'MESSAGE:CREATE',
  READ_MESSAGE = 'MESSAGE:READ',
  CONNECTION_ERROR = 'CONNECTION_ERROR',
  TYPING_MESSAGE = 'MESSAGE:TYPING',
  START_CALL = 'CALL:START',
  ACCEPT_CALL = 'CALL:ACCEPT',
  DECLINE_CALL = 'CALL:DECLINE',
  ADD_PEER = 'ADD_PEER',
  RELAY_ICE = 'RELAY_ICE',
  RELAY_SDP = 'RELAY_SDP',
  SESSION_DESCRIPTION = 'SESSION_DESCRIPTION',
  ICE_CANDIDATE = 'ICE_CANDIDATE',
}
